# Generated by Django 4.1.7 on 2023-05-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='technologies',
        ),
    ]
